DROP DATABASE THU;
CREATE DATABASE THU;
USE THU;
DROP TABLE `STUDENT`;
CREATE TABLE `STUDENT`(
STUDENTID TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`NAME`     VARCHAR(50)
);
DROP TABLE `MARK`;
CREATE TABLE `MARK`(
STUDENTID TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`TOTAL_MARKS`     VARCHAR(50)
);

INSERT INTO `STUDENT` (`NAME`)
			 VALUE    ('ABE'),
					  ('ABHAY'),
                      ('LON'),
                      ('BUOI');
                      
                      
 INSERT INTO `MARK` (`TOTAL_MARKS`)
			 VALUE    ('95'),
					   ('80'),
                       ('74'),
						('82');



SELECT S.`NAME`, M.TOTAL_MARKS
FROM (			SELECT S.`NAME`, M.TOTAL_MARKS
				FROM STUDENT AS S
				JOIN MARK AS M
				USING (STUDENTID) ) AS T
                
WHERE M.TOTAL_MARKS > ( SELECT  M.TOTAL_MARKS FROM (SELECT S.`NAME`, TOTAL_MARKS
													FROM MARK AS M
													WHERE S.`NAME`='ABHAY') 
); 





SELECT S.`NAME`, M.TOTAL_MARKS
FROM STUDENT AS S
JOIN MARK AS M
USING (STUDENTID)
WHERE S.`NAME`='ABHAY' 